### ISSUE TITLE
GridHelper.addToolbarFooter causes issues with column resizing.

### ISSUE THREAD

**Issue by brunoagretti** [FlowingCode/GridHelpers#60]
When GridHelper.addToolbarFooter is called within a grid, and this grid has columns with resizing enabled, the columns resizing behaves unproperly.
![captura2_360](https://user-images.githubusercontent.com/62401276/222191170-0609106b-89a7-4458-8b37-fecb2bb303cb.gif)

**Comment by javier-godoy** [comment]
Hello. Can you please attach some example code to reproduce the issue?

**Comment by brunoagretti** [comment]
Sure! It was an issue I had extendig Grid and adding a toolbarFooter:
```
public class CustomGrid<T> extends Grid<T>
{												

	public CustomGrid()
	{
	        ...
		setupGridExporter();
		...
	}
	
...

	protected void setupGridExporter()
	{
                // exportarPdfBtn is a regular vaadin Button and xlsLink is an anchor with a button inside
		HorizontalLayout toolbarFooterLayout = new HorizontalLayout(exportarPdfBtn, xlsLink);
		toolbarFooterLayout.setJustifyContentMode(JustifyContentMode.END);
		GridHelper.addToolbarFooter(this, toolbarFooterLayout);
	}
	
}
```
If columns added to this grid were set as rezisable, then `GridHelper.addToolbarFooter` will cause the behaviour shown above. I tried removing and adding `GridHelper.addToolbarFooter(this, toolbarFooterLayout);`  and the issue is only present when the toolbar is set.

**Comment by javier-godoy** [comment]
I enabled resizing in [GridExporterDemo](https://github.com/FlowingCode/GridExporterAddon/blob/master/src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemo.java) and the behavior is correct.
![grid](https://user-images.githubusercontent.com/11554739/231574241-41c3cb7a-7e9c-4e93-bde2-0e0ed967b7c6.gif)

Can you please attach a short self contained example? I guess that some other setting in your Grid may affect the behavior.
