### ISSUE TITLE
Setting a ResponsiveStep with 1000 minWith doesn´t work

### ISSUE THREAD

**Issue by federicoisaia** [FlowingCode/GridHelpers#93]
When setting a responsive step like this: 
```
GridHelper.responsiveStep(grid, 999).addListener(ge -> {
            grid.getColumnByKey("user-id-column").setVisible(true);
        });
```
I get the following behavior which is correct: 
![GridHelperBug](https://github.com/FlowingCode/GridHelpers/assets/82119455/11f890f3-7eb4-400b-af5f-0eb3389b0f21)

But when I set the minWith of the ResponsiveStep to 1000 (or bigger) this happens: 
![GridHelperBug1000](https://github.com/FlowingCode/GridHelpers/assets/82119455/a942bf6c-9566-4b3e-b65b-79605ac49058)

Is this a bug or am I doing something wrong?

**Comment by javier-godoy** [comment]
I meant a minimal reproducible example [[1]](https://stackoverflow.com/help/minimal-reproducible-example) [[2]](http://www.sscce.org/). What's the expected behavior and how does it differ from the observed behavior? What is the actual size of the grid in your example?
